apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-mongodb-app  
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-flask-mongodb-app  
  template:
    metadata:
      labels:
        app: my-flask-mongodb-app  
    spec:
      containers:
      - name: flask-web
        image: yourusername/flask-web-app:v1  
        ports:
        - containerPort: 8080
      - name: mongodb
        image: mongo:4.4  
        ports:
        - containerPort: 27017
